// KARTENDATEN
// alle karten sind hier als objekte gespeichert
// jede karte hat: id, titel, quelle, tag, label, likes, datum, bild, kommentare und axl-erklärung

const CARDS = [
  {
    id: 'europe-2nd-nationality',
    title: 'Europas 2. größte Nationalität',
    source: 'Brilliant Maps · Daten 2015',
    tag: 'Migration',
    label: 'ZWEITGRÖSSTE NATIONALITÄT · PRO LAND',
    likes: '4.7k',
    likesNum: 4700,
    dateAdded: Date.now() - 1000 * 60 * 60 * 48,
    image: 'maps/map1/Europe2ndnationality.png',
    comments: [
      { user: 'wien_daily',     text: 'Türkei in Österreich - macht Sinn, aber ich hätte auf Serbien getippt ehrlich gesagt.' },
      { user: 'migration_nerd', text: 'Die Russland-Dominanz im Osten zeigt wie tief die Sowjetzeit noch sitzt.' },
      { user: 'kurdinmap',      text: 'Dass Kurdistan als eigene Nation eingetragen ist - mutige Entscheidung vom Kartenmacher.' },
      { user: 'geo_petra',      text: 'Polen in 4 verschiedenen Ländern als Nr. 2 - die polnische Diaspora ist wirklich riesig.' },
    ],
    axo: 'Jedes Land trägt die Flagge seiner zweitgrößten Einwanderergruppe 🏳️ Was diese Karte zeigt, ist eigentlich Geschichte - Gastarbeiterprogramme, Kriege, der Zerfall der Sowjetunion. Türkische Flaggen in Deutschland, Österreich, Dänemark. Polnische Flaggen fast überall im Westen. Und im Osten? Fast immer Russland. Grenzen auf der Karte sind fest - Menschen waren es nie.',
  },
  {
    id: 'light-pollution',
    title: 'Lichtverschmutzung weltweit',
    source: 'Light Pollution Atlas · David Lorenz',
    tag: 'Klima',
    label: 'KÜNSTLICHE HELLIGKEIT DES NACHTHIMMELS',
    likes: '8.2k',
    likesNum: 8200,
    dateAdded: Date.now() - 1000 * 60 * 60 * 2,
    image: 'maps/map2/world-light-pollution.png',
    comments: [
      { user: 'sterngucker_at',  text: 'Nordkorea ist buchstäblich ein schwarzes Loch - aus dem Weltraum fast unsichtbar.' },
      { user: 'dark_sky_fan',    text: 'Europa leuchtet so stark dass man von Österreich aus kaum mehr die Milchstraße sieht. Traurig.' },
      { user: 'astro_max',       text: 'Das Niltal in Ägypten sieht man so deutlich - ein leuchtender Strich durch die Sahara.' },
      { user: 'licht_aus_bitte', text: 'Ich bin extra in die Steiermark gefahren um Sterne zu sehen. Hat sich gelohnt.' },
    ],
    axo: 'Der Unterschied zwischen arm und reich - einfach von oben fotografiert 🌃 Westeuropa, die US-Ostküste, Japan leuchten rot-weiß. Nordkorea? Fast komplett dunkel. Das Niltal zieht sich wie ein Leuchtfaden durch die Sahara. Und Sibirien - riesig, leer, schwarz. Wer noch echte Dunkelheit erleben will: es werden gerade die letzten Flecken knapper.',
  },
  {
    id: 'speed-limits',
    title: 'Tempolimits weltweit',
    source: 'Brilliant Maps · Wikipedia',
    tag: 'Verkehr',
    label: 'MAXIMALE AUTOBAHNGESCHWINDIGKEIT · KM/H',
    likes: '3.1k',
    likesNum: 3100,
    dateAdded: Date.now() - 1000 * 60 * 60 * 72,
    image: 'maps/map3/World_Speed_Limits.png',
    comments: [
      { user: 'autobahn_fan',  text: 'Deutschland ohne generelles Limit - der einzige dunkle Fleck in ganz Europa 😅' },
      { user: 'verkehr_nerd',  text: 'USA mit 70mph (112 km/h) auf Interstates fühlt sich nach Zeitreise an wenn man aus Europa kommt.' },
      { user: 'safe_roads_ch', text: 'Interessant dass die Länder mit 130 km/h nicht unbedingt mehr Unfälle haben als die mit 90.' },
      { user: 'reisender_mk',  text: 'Australien je nach Bundesstaat komplett unterschiedlich - das hab ich auf meiner Reise am eigenen Leib gespürt.' },
    ],
    axo: 'Eine Karte über Regeln - und was sie über Kulturen verraten 🚗 Deutschland ist der einzige größere Staat ohne generelles Autobahntempo. Die meisten Länder liegen bei 120-130 km/h. Aber schau auf Afrika und Teile Asiens: 90 km/h oder weniger, oft auf schlechteren Straßen. Tempolimits sind nicht nur Physik - sie sind Politik, Infrastruktur und nationale Identität in einem Schild.',
  },
  {
    id: 'europe-alcohol',
    title: 'Bier, Wein oder Schnaps?',
    source: 'WHO 2018 · Karte: Landgeist',
    tag: 'Geografie',
    label: 'MEISTKONSUMIERTES ALKOHOLGETRÄNK · EUROPA',
    likes: '11.4k',
    likesNum: 11400,
    dateAdded: Date.now() - 1000 * 60 * 60 * 20,
    image: 'maps/map4/europe-most-popular-alcoholic-drink.png',
    comments: [
      { user: 'weinkenner_at', text: 'Österreich Bierland - aber gefühlt trinken alle Wein hier?! Die Daten lügen nicht.' },
      { user: 'spirits_bro',   text: 'Die Schnaps-Zone im Osten macht absolut Sinn. Wodka ist da quasi Kulturerbe.' },
      { user: 'france_lover',  text: 'Frankreich Weinland - hätte ich jetzt nicht anders erwartet aber schön es bestätigt zu sehen 🍷' },
      { user: 'island_vibes',  text: 'Island Beer Country?? Dabei war Bier da bis 1989 verboten! Krasse Wendung.' },
    ],
    axo: 'Europa, aufgeteilt nach dem was abends im Glas landet 🍺🍷 Der Westen und Süden - Frankreich, Italien, Spanien, Portugal - trinken Wein. Der Norden und die Mitte - Deutschland, Österreich, Polen - greifen zum Bier. Im Osten, von der Ukraine bis Belarus, dominieren Spirituosen. Diese Karte ist eigentlich eine Karte der Kulturen, Klimate und Geschichte. Und Islands Bierkultur? Die ist erst seit 1989 legal.',
  },
];
